import * as React from "react";
type Link={label:string;href:string;external?:boolean}; type Section={title:string;links:Link[]}; type Config={name:string;sections:Section[];address:string;copyrightOwner:string;socials:Link[]};
const CONFIG:Record<string,Config>={
  technologies:{ name:"Zaza Technologies", sections:[ {title:"Company",links:[{label:"About",href:"https://zazatechnologies.com/about"},{label:"Blog",href:"https://zazatechnologies.com/blog"},{label:"Impressum",href:"/impressum"}]}, {title:"Products",links:[{label:"Zaza Teach",href:"https://zazateach.com"},{label:"Zaza Promptly",href:"https://zazapromptly.com"}]} ], address:"Zaza Technologies UG (haftungsbeschränkt) · Gumbertstraße 150 · 40229 Düsseldorf · Deutschland", copyrightOwner:"Zaza Technologies UG (haftungsbeschränkt)", socials:[{label:"TikTok",href:"https://www.tiktok.com/@zazatechnologies"},{label:"LinkedIn",href:"https://www.linkedin.com/company/zaza-technologies/"}] },
  teach:{ name:"Zaza Teach", sections:[ {title:"Resources",links:[{label:"Templates",href:"https://zazateach.com/templates"}]}, {title:"Company",links:[{label:"About",href:"https://zazateach.com/about"},{label:"Impressum",href:"/impressum"}]} ], address:"Zaza Technologies UG (haftungsbeschränkt) · Gumbertstraße 150 · 40229 Düsseldorf · Deutschland", copyrightOwner:"Zaza Technologies UG (haftungsbeschränkt)", socials:[{label:"X (ZazaTeach)",href:"https://x.com/zazateachapp"}] },
  promptly:{ name:"Zaza Promptly", sections:[ {title:"Product",links:[{label:"Overview",href:"https://zazapromptly.com"}]}, {title:"Legal",links:[{label:"Impressum",href:"/impressum"}]} ], address:"Zaza Technologies UG (haftungsbeschränkt) · Gumbertstraße 150 · 40229 Düsseldorf · Deutschland", copyrightOwner:"Zaza Technologies UG (haftungsbeschränkt)", socials:[{label:"X (ZazaTeach)",href:"https://x.com/zazateachapp"}] },
  realtyclose:{ name:"RealtyClose", sections:[ {title:"Product",links:[{label:"Docs",href:"https://realtyclose.com/docs"}]}, {title:"Company",links:[{label:"About",href:"https://realtyclose.com/about"},{label:"Impressum",href:"/impressum"}]} ], address:"Zaza Technologies UG (haftungsbeschränkt) · Gumbertstraße 150 · 40229 Düsseldorf · Deutschland", copyrightOwner:"Zaza Technologies UG (haftungsbeschränkt)", socials:[] },
};
export function Footer({product,locale="en"}:{product:keyof typeof CONFIG;locale?:string}){ const cfg=CONFIG[product]??CONFIG.technologies; return (<footer style={{borderTop:"1px solid #e5e5e5",marginTop:32,padding:"32px 0"}}><div style={{maxWidth:960,margin:"0 auto",padding:"0 16px"}}><div style={{fontWeight:600}}>{cfg.name}</div><div style={{display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:16,marginTop:16}}>{cfg.sections.map((s,idx)=>(<div key={idx}><div style={{fontWeight:600,marginBottom:8}}>{s.title}</div><ul style={{listStyle:"none",padding:0,margin:0}}>{s.links.map((l,i)=>(<li key={i}><a href={l.href}>{l.label}</a></li>))}</ul></div>))}</div><div style={{display:"flex",flexWrap:"wrap",gap:12,marginTop:16,opacity:.85}}>{cfg.socials.map((s,i)=>(<a key={i} href={s.href}>{s.label}</a>))}</div><div style={{marginTop:12,fontSize:12,opacity:.75}}>{cfg.address}</div><div style={{marginTop:4,fontSize:12,opacity:.75}}>© {new Date().getFullYear()} {cfg.copyrightOwner}</div></div></footer>); }
