name: Blog Content Guard
on:
  pull_request:
    paths:
      - "content/blog/**"
      - "src/content/authors/**"
      - "scripts/verify-blog.js"
      - ".github/workflows/content-guard.yml"
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - run: node scripts/verify-blog.js