name: Validate Content
on:
  pull_request:
    paths:
      - 'scripts/**'
      - '.github/workflows/validate-content.yml'
      - 'package.json'
      - 'pnpm-lock.yaml'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Type check (scoped)
        run: pnpm typecheck

      - name: Lint (validator only)
        run: pnpm lint:validator

      - name: Run content validator
        run: pnpm validate:content
