name: Validate Content

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/validate-content.yml"
      - "scripts/validate-content.ts"
      - "content/**"
      - "package.json"
      - "pnpm-lock.yaml"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      # Tolerant install so the job always runs
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      # (Optional) lint only the validator file so we don't lint the whole app
      - name: Lint validator
        run: pnpm exec eslint scripts/validate-content.ts --max-warnings=0

      # ✅ Run the validator itself
      - name: Validate content
        run: pnpm validate:content
