name: Validate Content

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/validate-content.yml"
      - "scripts/validate-content.ts"
      - "content/**"
      - "package.json"
      - "pnpm-lock.yaml"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Ensure pnpm is available on the runner
      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      # ✅ Make install tolerant so the job runs even if the lockfile is missing
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Type check
        run: pnpm typecheck

      - name: Lint code
        run: pnpm lint

      - name: Validate content
        run: pnpm validate:content
